name: CI/CD - Inventory Service

on:
  push:
    paths:
      - 'inventory-service/**'
  pull_request:
    paths:
      - 'inventory-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Step 3: Build the inventory-service module
      - name: Build Inventory Service
        run: mvn -pl inventory-service -am clean package -DskipTests

      # Step 4: Run unit tests
      - name: Run unit tests
        run: mvn test -pl inventory-service

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 6: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Build and Push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: inventory-service/Dockerfile
          push: true
          tags: harshvardhansingh7/ecommerce-microservices:inventory-service-latest
